services:
  postgresql:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=mais
      - TZ=America/Sao_Paulo
    volumes:
      - mais_pg_data:/bitnami/postgresql

volumes:
  mais_pg_data:
